//
// Created by redkc on 05/03/2026.
//

#ifndef REASONABLEVULKAN_SHADERDEFINITIONENUM_HPP
#define REASONABLEVULKAN_SHADERDEFINITIONENUM_HPP

    enum ShaderDefinesEnum {
    SCENE_UBO_GLSL,
    VERTEX_IO_GLSL,
    LIGHTING_COMMON_GLSL,
    MATERIAL_PBR_GLSL,
    MODEL_PC_GLSL,
    LIGHT_MODEL_PC_GLSL,
    MATERIAL_SKYBOX_GLSL,
    WIREMESH_GLSL,
    ENABLE_MULTVIEW
};

#endif //REASONABLEVULKAN_SHADERDEFINITIONENUM_HPP